ARG TAG_NAME="latest"
FROM awiciroh/forcingprocessor-deps:${TAG_NAME} AS forcingprocessor_base
COPY . /forcingprocessor/
RUN uv pip install --system -e /forcingprocessor && \
    uv pip install --system pytest && \
    groupadd -r mygroup && useradd -r -g mygroup myuser && \
    chown -R myuser:mygroup /forcingprocessor
