ARG TAG_NAME="latest"
FROM awiciroh/forcingprocessor-deps:${TAG_NAME} AS forcingprocessor_base
COPY forcingprocessor/ /forcingprocessor/
RUN pip3 install -e /forcingprocessor && \
    groupadd -r mygroup && useradd -r -g mygroup myuser && \
    chown -R myuser:mygroup /ngen-datastream
