ARG TAG_NAME="latest"
FROM awiciroh/forcingprocessor-deps:${TAG_NAME} AS forcingprocessor_base
COPY . /forcingprocessor/
RUN ln -sf /usr/bin/python3.11 /usr/bin/python3 && \
    uv pip install --system --python python3.11 -e /forcingprocessor && \
    uv pip install --system --python python3.11 pytest && \
    groupadd -r mygroup && useradd -r -g mygroup myuser && \
    chown -R myuser:mygroup /forcingprocessor
