name: Build and Test Forcing Processor with Datastream
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to build from (leave empty to use current branch)'
        required: false
        default: ''
        type: string
      ds_tag:
        description: 'DS_TAG for datastream testing (leave empty for latest)'
        required: false
        default: ''
        type: string
  push:
    branches:
      - main
      - fp_workflow
      - trivy_scan
    paths:
      - 'docker/**' 
      - 'src/forcingprocessor/**'
      - '!src/forcingprocessor/README.md'
  pull_request:
    paths:
      - 'docker/**' 
      - 'src/forcingprocessor/**'
      - '!src/forcingprocessor/README.md'

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF results

jobs:
  build-test-docker-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
    - name: Build docker containers
      run: |
        docker system prune -a
        ARCH=x86 TAG=latest-x86 docker compose -f docker/docker-compose.yml build forcingprocessor-deps
        TAG=latest-x86 docker compose -f docker/docker-compose.yml build forcingprocessor
    - name: clone ngen
      run: |
        git clone --single-branch --branch main --depth 1 https://github.com/CIROH-UA/ngen-datastream.git
    - name: Run Trivy vulnerability scan - deps (SARIF for GitHub)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'awiciroh/forcingprocessor-deps:latest-x86'
        format: 'sarif'
        output: 'trivy-deps-x86-results.sarif'
        severity: 'CRITICAL'

    - name: Run Trivy vulnerability scan - deps (JSON for artifacts)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'awiciroh/forcingprocessor-deps:latest-x86'
        format: 'json'
        output: 'trivy-deps-x86-results.json'
        severity: 'CRITICAL'

    - name: Upload Trivy scan results - deps
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-deps-x86-results.sarif'
        category: 'trivy-deps-x86'

    - name: Run Trivy vulnerability scan - fp (SARIF for GitHub)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'awiciroh/forcingprocessor:latest-x86'
        format: 'sarif'
        output: 'trivy-fp-x86-results.sarif'
        severity: 'CRITICAL'

    - name: Run Trivy vulnerability scan - fp (JSON for artifacts)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'awiciroh/forcingprocessor:latest-x86'
        format: 'json'
        output: 'trivy-fp-x86-results.json'
        severity: 'CRITICAL'

    - name: Upload Trivy scan results - fp
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-fp-x86-results.sarif'
        category: 'trivy-fp-x86'

    - name: Save Trivy results as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-results-x86
        path: |
          trivy-deps-x86-results.json
          trivy-fp-x86-results.json
          trivy-deps-x86-results.sarif
          trivy-fp-x86-results.sarif
        retention-days: 10

    - name: Prepare and test docker containers
      run: |
        cd ngen-datastream
        curl -L -O https://ngen-datastream.s3.us-east-2.amazonaws.com/palisade.gpkg
        if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.ds_tag }}" ]; then
          DS_TAG="${{ inputs.ds_tag }}-x86"
          echo "Using manual input DS_TAG: $DS_TAG"
        else
          DS_TAG="latest-x86"
          echo "Using default DS_TAG: $DS_TAG"
        fi
        echo $DS_TAG
        export DS_TAG=$DS_TAG FP_TAG=latest-x86 && ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g $(pwd)/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json -n 4
  build-test-docker-arm:
    needs: [build-test-docker-x86]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
      - name: clone ngen
        run: |
          git clone --single-branch --branch main --depth 1 https://github.com/CIROH-UA/ngen-datastream.git
              
      - name: Prepare execution config with branch
        run: |
          # Determine the branch name
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.branch_name }}" ]; then
            BRANCH_NAME="${{ inputs.branch_name }}"
            echo "Using manual input branch: $BRANCH_NAME"
          else
            BRANCH_NAME="${{ github.ref_name }}"
            echo "Using current branch: $BRANCH_NAME"
          fi
          # Replace ${BRANCH_NAME} with actual branch name in the file
          cd $GITHUB_WORKSPACE/.github/executions
          sed -i "s#\${BRANCH_NAME}#$BRANCH_NAME#g" test_execution_gp_arm_docker_buildNtester.json
          cat test_execution_gp_arm_docker_buildNtester.json
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.ds_tag }}" ]; then
            DS_TAG="${{ inputs.ds_tag }}-arm64"
            echo "Using manual input branch: $DS_TAG"
          else
            DS_TAG="latest-arm64"
            echo "Using DS TAG: $DS_TAG"
          fi
          
          # Replace ${DS_TAG} with actual DS_TAG in the file
          cd $GITHUB_WORKSPACE/.github/executions
          sed -i "s/\${DS_TAG}/$DS_TAG/g" test_execution_gp_arm_docker_buildNtester.json
          cat test_execution_gp_arm_docker_buildNtester.json
      - name: Build AWS Infra
        run: |
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          terraform init
          terraform validate
          ../scripts/import_resources.sh ./test/variables_gitactions_arm.tfvars
          terraform apply -var-file=./test/variables_gitactions_arm.tfvars -auto-approve
          sleep 60
          
      - name: Set permissions
        run: |
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          aws iam attach-role-policy --role-name datastream_ec2_role_github_actions_arm --policy-arn arn:aws:iam::aws:policy/SecretsManagerReadWrite
          aws secretsmanager put-resource-policy --secret-id docker_awiciroh_creds --resource-policy file://test/secret-policy.json --block-public-policy --region us-east-1
          if ! aws ec2 describe-key-pairs --key-names "actions_key_arm" --query 'KeyPairs[0].KeyName' --output text 2>/dev/null; then aws ec2 create-key-pair --key-name "actions_key_arm" --query 'KeyName' --output text && echo "Key pair 'actions_key_arm' created in AWS"; else echo "Key pair 'actions_key_arm' already exists"; fi
          sleep 60
      
      - name: Build and Test arm docker containers with AWS infra
        run: |
          cat $GITHUB_WORKSPACE/.github/executions/test_execution_gp_arm_docker_buildNtester.json
          cp $GITHUB_WORKSPACE/.github/executions/test_execution_gp_arm_docker_buildNtester.json $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform/test/execution_gp_arm_docker_buildNtester.json
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://test/execution_gp_arm_docker_buildNtester.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
      
      - name: Get EC2 instance ID for Trivy scan
        id: get-instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=datastream_github_actions_arm" "Name=instance-state-name,Values=running" \
            --query 'Reservations[0].Instances[0].InstanceId' \
            --output text \
            --region us-east-1)
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "Found instance: $INSTANCE_ID"
      - name: Run Trivy scan on ARM images via SSM
        run: |
          INSTANCE_ID="${{ steps.get-instance.outputs.instance_id }}"
          
          # Install Trivy on the ARM instance
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release","wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -","echo \"deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main\" | sudo tee -a /etc/apt/sources.list.d/trivy.list","sudo apt-get update && sudo apt-get install -y trivy"]' \
            --region us-east-1 \
            --query 'Command.CommandId' \
            --output text)
          
          aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --region us-east-1
          
          # Scan deps image
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["trivy image --format sarif --output /tmp/trivy-deps-arm-results.sarif --severity CRITICAL awiciroh/forcingprocessor-deps:latest-arm64"]' \
            --region us-east-1 \
            --query 'Command.CommandId' \
            --output text)
          
          aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --region us-east-1
          
          # Scan fp image
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["trivy image --format sarif --output /tmp/trivy-fp-arm-results.sarif --severity CRITICAL awiciroh/forcingprocessor:latest-arm64"]' \
            --region us-east-1 \
            --query 'Command.CommandId' \
            --output text)
          
          aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --region us-east-1
      - name: Download ARM Trivy results
        run: |
          INSTANCE_ID="${{ steps.get-instance.outputs.instance_id }}"
          
          # Copy results using SSM
          UPLOAD_COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["aws s3 cp /tmp/trivy-deps-arm-results.sarif s3://trivy-scan-results-ua/trivy-results/","aws s3 cp /tmp/trivy-fp-arm-results.sarif s3://trivy-scan-results-ua/trivy-results/"]' \
            --region us-east-1 \
            --query 'Command.CommandId' \
            --output text)
          # Wait for upload to complete
          aws ssm wait command-executed --command-id "$UPLOAD_COMMAND_ID" --instance-id "$INSTANCE_ID" --region us-east-1
          # Download from S3
          mkdir -p trivy-arm-results
          aws s3 cp s3://trivy-scan-results-ua/trivy-results/trivy-deps-arm-results.sarif ./trivy-arm-results/
          aws s3 cp s3://trivy-scan-results-ua/trivy-results/trivy-fp-arm-results.sarif ./trivy-arm-results/
      - name: Upload Trivy scan results - ARM deps
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-arm-results/trivy-deps-arm-results.sarif'
          category: 'trivy-deps-arm64'

      - name: Upload Trivy scan results - ARM fp
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-arm-results/trivy-fp-arm-results.sarif'
          category: 'trivy-fp-arm64'

      - name: Save ARM Trivy results as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-results-arm64
          path: trivy-arm-results/
          retention-days: 90

      - name: Tear down infra
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          terraform destroy -var-file=./test/variables_gitactions_arm.tfvars -auto-approve
          sleep 30