name: Build, Test, and Push Datastream Docker Containers on X86 and ARM (Version Aware)

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to build from (leave empty to use current branch)'
        required: false
        default: ''
        type: string
      ds_tag:
        description: 'DS_TAG for datastream testing (leave empty for latest)'
        required: false
        default: ''
        type: string
  push:
    # branches:
    #   - main
    paths:
      - 'versions.yml'

permissions:
  contents: read   

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      build_deps: ${{ steps.changes.outputs.build_deps }}
      deps_version: ${{ steps.changes.outputs.deps_version }}
      build_fp: ${{ steps.changes.outputs.build_fp }}
      fp_version: ${{ steps.changes.outputs.fp_version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 2

    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Detect version changes
      id: changes
      shell: bash
      run: |
        set -euo pipefail
    
        # Current versions (raw)
        CURRENT_DEPS=$(yq -r e '."forcingprocessor-deps"' versions.yml)
        CURRENT_FP=$(yq -r e '.forcingprocessor' versions.yml)
    
        # Ensure previous commit and file exist
        if git rev-parse HEAD~1 >/dev/null 2>&1 && git cat-file -e HEAD~1:versions.yml 2>/dev/null; then
          git show HEAD~1:versions.yml > previous_versions.yml
        else
          printf "forcingprocessor-deps: '0.0.0'\nforcingprocessor: '0.0.0'\n" > previous_versions.yml
        fi
    
        PREVIOUS_DEPS=$(yq -r e '."forcingprocessor-deps"' previous_versions.yml)
        PREVIOUS_FP=$(yq -r e '.forcingprocessor' previous_versions.yml)
    
        # Check what changed and set outputs
        if [ "$CURRENT_DEPS" != "$PREVIOUS_DEPS" ]; then
          echo "forcingprocessor-deps changed: $PREVIOUS_DEPS -> $CURRENT_DEPS"
          echo "build_deps=true" >> "$GITHUB_OUTPUT"
        else
          echo "build_deps=false" >> "$GITHUB_OUTPUT"
        fi
        echo "deps_version=$CURRENT_DEPS" >> "$GITHUB_OUTPUT"
    
        if [ "$CURRENT_FP" != "$PREVIOUS_FP" ]; then
          echo "forcingprocessor changed: $PREVIOUS_FP -> $CURRENT_FP"
          echo "build_fp=true" >> "$GITHUB_OUTPUT"
        else
          echo "build_fp=false" >> "$GITHUB_OUTPUT"
        fi
        echo "fp_version=$CURRENT_FP" >> "$GITHUB_OUTPUT"
    

  build-test-push-docker-x86:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Install packages for datastream
    #   run: |
    #     curl -L -O https://github.com/lynker-spatial/hfsubsetCLI/releases/download/v1.1.0/hfsubset-v1.1.0-linux_amd64.tar.gz && tar -xzvf hfsubset-v1.1.0-linux_amd64.tar.gz && sudo mv ./hfsubset /usr/bin/hfsubset && sudo apt-get update && sudo apt-get install git pip pigz -y        

    - name: Build and push deps image first
      run: |
        # Build deps image with latest-x86 tag (Ubuntu-based)
        export ARCH=x86
        export TAG=latest-x86
        echo "Building Ubuntu-based deps with TAG=$TAG"
        
        # Build and push deps image - this will overwrite any old Amazon Linux image
        docker compose -f docker/docker-compose.yml build forcingprocessor-deps
        docker images awiciroh/forcingprocessor-deps:latest-x86
        
        # Push deps image immediately to overwrite old version
        if [ "${{ needs.detect-changes.outputs.build_deps }}" == "true" ]; then
          VERSION_TAG="${{ needs.detect-changes.outputs.deps_version }}"
          docker tag awiciroh/forcingprocessor-deps:latest-x86 awiciroh/forcingprocessor-deps:${VERSION_TAG}-x86
          docker push awiciroh/forcingprocessor-deps:${VERSION_TAG}-x86
        fi
        docker push awiciroh/forcingprocessor-deps:latest-x86
        echo "Ubuntu-based deps image pushed to registry as latest-x86"

    - name: Build main docker image
      run: |
        # Build main image - it will pull the fresh Ubuntu-based deps from registry
        echo "Building main image using latest-x86 deps (Ubuntu-based)"
        
        # Force pull fresh deps image to ensure we get Ubuntu version
        echo "Pulling fresh Ubuntu-based deps image:"
        docker pull awiciroh/forcingprocessor-deps:latest-x86
        
        # Build main image using docker-compose with latest-x86
        export TAG=latest-x86
        export ARCH=x86
        docker compose -f docker/docker-compose.yml build forcingprocessor
        
        docker images awiciroh/forcingprocessor:latest-x86

    - name: clone ngen
      run: |
        git clone --single-branch --branch main --depth 1 https://github.com/CIROH-UA/ngen-datastream.git
  
    - name: Prepare and test docker containers
      run: |
        cd ngen-datastream
        curl -L -O https://ngen-datastream.s3.us-east-2.amazonaws.com/palisade.gpkg
        if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.ds_tag }}" ]; then
          DS_TAG="${{ inputs.ds_tag }}-x86"
          echo "Using manual input DS_TAG: $DS_TAG"
        else
          DS_TAG="latest-x86"
          echo "Using default DS_TAG: $DS_TAG"
        fi
        FP_TAG="latest-x86"
        echo "Using FP_TAG: $FP_TAG"
        export DS_TAG=$DS_TAG FP_TAG=$FP_TAG && ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g $(pwd)/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json -n 4

    - name: Push main docker image
      run: |
        # Push main image (latest-x86 already built and tagged)
        if [ "${{ needs.detect-changes.outputs.build_fp }}" == "true" ]; then
          VERSION_TAG="${{ needs.detect-changes.outputs.fp_version }}"
          docker tag awiciroh/forcingprocessor:latest-x86 awiciroh/forcingprocessor:${VERSION_TAG}-x86
          docker push awiciroh/forcingprocessor:${VERSION_TAG}-x86
        fi
        docker push awiciroh/forcingprocessor:latest-x86


  build-test-push-docker-arm:
    needs: [detect-changes, build-test-push-docker-x86]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: clone ngen
        run: |
          git clone --single-branch --branch main --depth 1 https://github.com/CIROH-UA/ngen-datastream.git
              
      - name: Prepare execution config with branch
        run: |
          # Determine the branch name
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.branch_name }}" ]; then
            BRANCH_NAME="${{ inputs.branch_name }}"
            echo "Using manual input branch: $BRANCH_NAME"
          else
            BRANCH_NAME="${{ github.ref_name }}"
            echo "Using current branch: $BRANCH_NAME"
          fi
          
          # Replace ${BRANCH_NAME} with actual branch name in the file
          cd $GITHUB_WORKSPACE/.github/executions
          sed -i "s/\${BRANCH_NAME}/$BRANCH_NAME/g" execution_gp_arm_docker_buildNtester.json
          cat execution_gp_arm_docker_buildNtester.json

          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.ds_tag }}" ]; then
            DS_TAG="${{ inputs.ds_tag }}-arm64"
            echo "Using manual input branch: $DS_TAG"
          else
            DS_TAG="latest-arm64"
            echo "Using DS TAG: $DS_TAG"
          fi
          # Replace ${DS_TAG} with actual DS_TAG in the file
          cd $GITHUB_WORKSPACE/.github/executions
          sed -i "s/\${DS_TAG}/$DS_TAG/g" execution_gp_arm_docker_buildNtester.json
          cat execution_gp_arm_docker_buildNtester.json



      - name: Build AWS Infra
        run: |
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          terraform init
          terraform validate
          ../scripts/import_resources.sh ./test/variables_gitactions_arm.tfvars
          terraform apply -var-file=./test/variables_gitactions_arm.tfvars -auto-approve
          sleep 60
          
      - name: Set permissions
        run: |
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          aws iam attach-role-policy --role-name datastream_ec2_role_github_actions_arm --policy-arn arn:aws:iam::aws:policy/SecretsManagerReadWrite
          aws secretsmanager put-resource-policy --secret-id docker_awiciroh_creds --resource-policy file://test/secret-policy.json --block-public-policy --region us-east-1
          if ! aws ec2 describe-key-pairs --key-names "actions_key_arm" --query 'KeyPairs[0].KeyName' --output text 2>/dev/null; then aws ec2 create-key-pair --key-name "actions_key_arm" --query 'KeyName' --output text && echo "Key pair 'actions_key_arm' created in AWS"; else echo "Key pair 'actions_key_arm' already exists"; fi
          sleep 60
      
      - name: Build and Test arm docker containers with AWS infra
        run: |
          BUILD_FLAGS=""
          TAG=""
          
          if [ "${{ needs.detect-changes.outputs.build_fp }}" == "true" ]; then
            BUILD_FLAGS="$BUILD_FLAGS -f"
            TAG="${{ needs.detect-changes.outputs.fp_version }}-arm64"
          fi
          if [ "${{ needs.detect-changes.outputs.build_deps }}" == "true" ]; then
            BUILD_FLAGS="$BUILD_FLAGS -e"
            TAG="${{ needs.detect-changes.outputs.deps_version }}-arm64"
          fi
          if [ -z "$BUILD_FLAGS" ]; then 
            echo "No components changed, skipping ARM build"
            exit 0
          fi
          
          if [ -z "$TAG" ]; then
            TAG="latest-arm64"
          fi
          
          BUILD_FLAGS=$(echo "$BUILD_FLAGS" | sed 's/^ *//')  
      
          sed -i -e "s/\${TAG}/$TAG/g" -e "s/\${BUILD_ARGS}/$BUILD_FLAGS/g" \
            $GITHUB_WORKSPACE/.github/executions/execution_gp_arm_docker_buildNtester.json
          
          echo "Generated execution file:"
          cat $GITHUB_WORKSPACE/.github/executions/execution_gp_arm_docker_buildNtester.json
          cp $GITHUB_WORKSPACE/.github/executions/execution_gp_arm_docker_buildNtester.json $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform/test/execution_gp_arm_docker_buildNtester.json
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          echo "Building with TAG: $TAG and FLAGS: $BUILD_FLAGS"
          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://test/execution_gp_arm_docker_buildNtester.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
      
      - name: Tear down infra
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/ngen-datastream/research_datastream/terraform
          terraform destroy -var-file=./test/variables_gitactions_arm.tfvars -auto-approve
          sleep 30

  create-manifest:
    name: Create and Push Manifest
    needs: [detect-changes, build-test-push-docker-arm]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push manifest forcingprocessor-deps
        if: needs.detect-changes.outputs.build_deps == 'true'
        run: |
          docker manifest create awiciroh/forcingprocessor-deps:${{ needs.detect-changes.outputs.deps_version }} \
            --amend awiciroh/forcingprocessor-deps:${{ needs.detect-changes.outputs.deps_version }}-x86 \
            --amend awiciroh/forcingprocessor-deps:${{ needs.detect-changes.outputs.deps_version }}-arm64
          docker manifest push awiciroh/forcingprocessor-deps:${{ needs.detect-changes.outputs.deps_version }}

          docker manifest create awiciroh/forcingprocessor-deps:latest \
            --amend awiciroh/forcingprocessor-deps:latest-x86 \
            --amend awiciroh/forcingprocessor-deps:latest-arm64
          docker manifest push awiciroh/forcingprocessor-deps:latest

      - name: Create and push manifest forcingprocessor
        if: needs.detect-changes.outputs.build_fp == 'true'
        run: |
          docker manifest create awiciroh/forcingprocessor:${{ needs.detect-changes.outputs.fp_version }} \
            --amend awiciroh/forcingprocessor:${{ needs.detect-changes.outputs.fp_version }}-x86 \
            --amend awiciroh/forcingprocessor:${{ needs.detect-changes.outputs.fp_version }}-arm64
          docker manifest push awiciroh/forcingprocessor:${{ needs.detect-changes.outputs.fp_version }}

          docker manifest create awiciroh/forcingprocessor:latest \
            --amend awiciroh/forcingprocessor:latest-x86 \
            --amend awiciroh/forcingprocessor:latest-arm64
          docker manifest push awiciroh/forcingprocessor:latest