# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Forcing Processor Amazon Cloud Sources
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/forcingprocessor/**'
      - '!src/forcingprocessor/README.md'
      - 'pyproject.toml'
      - 'setup.cfg'
      - '.python-version'
  pull_request:
    branches:
      - main
    paths:
      - 'src/forcingprocessor/**'
      - '!src/forcingprocessor/README.md'
      - 'pyproject.toml'
      - 'setup.cfg'
      - '.python-version'

permissions:
  id-token: write
  contents: read
jobs:
  test-forcingprocessor:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Test with pytest
        run: |
          python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_noaa_nwm_pds_https 
          # These all are matched with -k test_noaa_nwm_pds_https 
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_noaa_nwm_pds_https_short_range 
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_noaa_nwm_pds_https_medium_range
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_noaa_nwm_pds_https_analysis_assim
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_noaa_nwm_pds_https_analysis_assim_extend

          python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_noaa_nwm_pds_s3 

          python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_retro
          # These all are matched with -k test_retro 
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_retro_2_1_https 
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_retro_2_1_s3
          # python -m pytest -q --tb=short --disable-warnings --maxfail=1 -k test_retro_3_0          